app1/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.indexpage,name='index.html')

]

credentials/urls.py
from django.urls import path
from . import views

app_name="credentials"

urlpatterns = [
    path('register/',views.register,name='register'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout')

]

project1/urls.py
from django.contrib import admin
from django.urls import path,include
from project1 import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app1.urls')),
    path('credentials/',include('credentials.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


app1/models.py
from django.db import models

class place(models.Model):
    name= models.CharField(max_length=250)
    img = models.ImageField(upload_to='pics')
    desc = models.TextField()

    def __str__(self):
        return self.name

class people(models.Model):
    name = models.CharField(max_length=250)
    img = models.ImageField(upload_to='pics')
    desc = models.TextField()

    def __str__(self):
        return self.name

credentials/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render
from .models import place,people


def indexpage(request):
    obj = place.objects.all()
    obj1 = people.objects.all()
    return render(request,'index.html',{'result':obj,'result1':obj1})

credentials/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib import messages, auth


def register(request):
    if request.method=='POST':
        username=request.POST['username']
        firstname=request.POST['first_name']
        lastname=request.POST['last_name']
        email=request.POST['email']
        password=request.POST['password']
        cpassword=request.POST['cpassword']

        if password==cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request,'username taken')
                return redirect('/credentials/register')

            elif User.objects.filter(email=email).exists():
                messages.info(request,'email taken')
                return redirect('/credentials/register')

            else:
                user=User.objects.create_user(username=username,password=password,first_name=firstname,last_name=lastname,email=email)
                user.save();
                return redirect('/credentials/login')
        else:
            messages.info(request,'password not matching')
            return redirect('/credentials/register')

        return redirect('/')

    return render(request,'register.html')

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return redirect('/')
        else:
            messages.info(request,'invalid credentials')
            return redirect('/credentials/login')

    return render(request,'login.html')

def logout(request):
    auth.logout(request)
    return redirect('/')

templates/demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>demo page</title>
</head>
<body>
hello there
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
<form action="{% url 'credentials:login' %}" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="enter your username"><br>
    <input type="password" name="password" placeholder="enter ur password"><br>
    <input type="submit">
</form>
{% for msg in messages %}
<h2>{{msg}}</h2>
{% endfor %}
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>register page</title>
</head>
<body>
<form action="{% url 'credentials:register' %}" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="username"><br>
    <input type="text" name="first_name" placeholder="first name"><br>
    <input type="text" name="last_name" placeholder="last name"><br>
    <input type="email" name="email" placeholder="email"><br>
    <input type="password" name="password" placeholder="password"><br>
    <input type="password" name="cpassword" placeholder="confirm password"><br>
    <input type="submit">
</form>
{% for msg in messages %}
<h2>{{msg}}</h2>
{% endfor %}
</body>
</html>